[package]
name = "day11"
version = "0.1.0"
authors = ["Reid Swan <reidswan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }